chapter_3:
  title: "C# 3: LINQ and Everything That Comes With It"
  overview:
    duration_min: 15
    description: "Read the chapter introduction, objectives, and get a high-level view of LINQ features."
  sections:
    - id: "3.1"
      title: "Automatically Implemented Properties"
      duration_min: 15
      description: "Study auto-property syntax, default values, and scenarios for use."
    - id: "3.2"
      title: "Implicit Typing"
      duration_min: 15
      description: "Explore implicit typing and how it simplifies variable declarations."
      subsections:
        - id: "3.2.1"
          title: "Typing Terminology"
          duration_min: 5
          description: "Learn the key terms around typing in C#."
        - id: "3.2.2"
          title: "Implicitly Typed Local Variables (var)"
          duration_min: 5
          description: "Practice declaring and using 'var' in real examples."
        - id: "3.2.3"
          title: "Implicitly Typed Arrays"
          duration_min: 5
          description: "Understand how implicitly typed arrays work and when to use them."
    - id: "3.3"
      title: "Object and Collection Initializers"
      duration_min: 20
      description: "Examine initializer syntax for objects and collections."
      subsections:
        - id: "3.3.1"
          title: "Introduction to Initializers"
          duration_min: 5
          description: "Read the rationale and basic form of object and collection initializers."
        - id: "3.3.2"
          title: "Object Initializers"
          duration_min: 5
          description: "Walk through object-initializer examples and patterns."
        - id: "3.3.3"
          title: "Collection Initializers"
          duration_min: 5
          description: "Try collection-initializer syntax on sample data."
        - id: "3.3.4"
          title: "Benefits of Single-Expression Initialization"
          duration_min: 5
          description: "Note why expression-based initialization can be more concise."
    - id: "3.4"
      title: "Anonymous Types"
      duration_min: 15
      description: "Deep-read anonymous-type usage and compiler behaviors."
      subsections:
        - id: "3.4.1"
          title: "Syntax and Basic Behavior"
          duration_min: 5
          description: "Study the syntax rules for anonymous types."
        - id: "3.4.2"
          title: "The Compiler-Generated Type"
          duration_min: 5
          description: "Inspect what the compiler generates under the covers."
        - id: "3.4.3"
          title: "Limitations"
          duration_min: 5
          description: "List scenarios where anonymous types fall short."
    - id: "3.5"
      title: "Lambda Expressions"
      duration_min: 25
      description: "Dive into lambda syntax, closures, and expression trees."
      subsections:
        - id: "3.5.1"
          title: "Lambda Expression Syntax"
          duration_min: 5
          description: "Learn the basic form and variations of lambda expressions."
        - id: "3.5.2"
          title: "Capturing Variables"
          duration_min: 10
          description: "Experiment with closures and variable capture in lambdas."
        - id: "3.5.3"
          title: "Expression Trees"
          duration_min: 10
          description: "Understand expression-tree fundamentals and use cases."
    - id: "3.6"
      title: "Extension Methods"
      duration_min: 15
      description: "Learn to extend existing types with your own methods."
      subsections:
        - id: "3.6.1"
          title: "Declaring an Extension Method"
          duration_min: 5
          description: "Write and compile a basic extension method."
        - id: "3.6.2"
          title: "Invoking an Extension Method"
          duration_min: 5
          description: "Use your extension method in sample code."
        - id: "3.6.3"
          title: "Chaining Method Calls"
          duration_min: 5
          description: "Chain multiple extensions in a fluent style."
    - id: "3.7"
      title: "Query Expressions"
      duration_min: 20
      description: "Explore LINQ query syntax and when to use it."
      subsections:
        - id: "3.7.1"
          title: "Query Expressions → Method Calls"
          duration_min: 5
          description: "See how query syntax compiles into method calls."
        - id: "3.7.2"
          title: "Range Variables & Transparent Identifiers"
          duration_min: 5
          description: "Understand the role of range variables in queries."
        - id: "3.7.3"
          title: "Choosing Syntax: Query vs. Method Chaining"
          duration_min: 10
          description: "Compare query syntax against method-chain syntax."
    - id: "3.8"
      title: "The End Result: LINQ"
      duration_min: 15
      description: "Review full end-to-end LINQ examples and real-world patterns."
    - id: "summary"
      title: "Summary"
      duration_min: 15
      description: "Summarize key takeaways, create flashcards, and note any questions."
